services:
  - type: web
    name: tech-time-capsule-api
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: "pipenv install --system --deploy && flask db upgrade && flask seed_db"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tech-capsule-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.1"
      - key: FLASK_APP
        value: "wsgi.py" 
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: tech-time-capsule-client
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./build"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: tech-capsule-db
    plan: free
    region: frankfurt